name: continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: continuous integration
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          cache: 'gradle'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Run gradle check
        uses: burrunan/gradle-cache-action@v1
        continue-on-error: false
        with:
          arguments: check
          gradle-version: wrapper
