name: continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: publish to docker hub
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
        
      - name: test workflow
        run: echo $DOCKER_USER
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -f dockerfile -t gabrielleeg1/arcano:latest

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: gabrielleeg1/arcano

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
